# Prometheus Docker compose project
#
# SEE ALSO
# 1. https://hub.docker.com/r/prom/prometheus
#
---

#version: '3.8'

networks:
    traefik-proxy:
      external: true
      driver: overlay
      attachable: true

volumes:
    prometheus_cache:
      external: false

services:
    prometheus:
      restart: always
      image: prom/prometheus:v2.53.5
      container_name: prometheus-1
      networks:
        - traefik-proxy
      ports:
        - "9090:9090"
      volumes:
        - ./mounts/config/prometheus.yml:/etc/prometheus/prometheus.yml
          # Persistant Prometheus cache; aggregation of time series data...
        - prometheus_cache:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-lifecycle' # Allows reloading config without restarting
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus-fs1.rule=Host(`prometheus.fs1.home`) && PathPrefix(`/`)"
        - "traefik.http.routers.prometheus-fs1.entrypoints=websecure"
        - "traefik.http.services.prometheus-fs1.loadbalancer.server.port=9090"
        - "traefik.http.routers.prometheus-fs1.service=prometheus-fs1"

    #node_exporter:
      #image: prom/node-exporter
      #container_name: node_exporter
      #ports:
      #- "9100:9100"
      #volumes:
      #- /proc:/host/proc:ro
      #- /sys:/host/sys:ro
      #- /:/rootfs:ro
      #command:
      #- '--path.procfs=/host/proc'
      #- '--path.sysfs=/host/sys'
      #- '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

