#
---

#version: '3.8'

networks:
    traefik-proxy:
      external: true
      driver: overlay
      attachable: true

volumes:
    prometheus_cache:
      external: false

services:
    prometheus:
      restart: always
      image: prom/prometheus:latest
      container_name: prometheus-1
      networks:
        - traefik-proxy
      ports:
        - "9090:9090"
        #- "11090:9090"
      volumes:
        - ./mounts/config/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_cache:/prometheus # Persist Prometheus data
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-lifecycle' # Allows reloading config without restarting

    #node_exporter:
      #image: prom/node-exporter
      #container_name: node_exporter
      #ports:
      #- "9100:9100"
      #volumes:
      #- /proc:/host/proc:ro
      #- /sys:/host/sys:ro
      #- /:/rootfs:ro
      #command:
      #- '--path.procfs=/host/proc'
      #- '--path.sysfs=/host/sys'
      #- '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

